trigger:
  branches:
    include:
      - main  # Adjust to your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'  # Copy all files from the source directory
    Contents: '**'  # Include all files and folders
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Copy to the staging directory

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Publish the files from the staging directory as build artifacts
    ArtifactName: 'drop'  # Name of the artifact
    publishLocation: 'Container'  # Publish to Azure Pipelines artifacts

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Web App Service Connection'  # Specify the name of your Azure service connection
    appName: 'theracingpuzzle'  # Specify the name of your Azure Web App
    package: '$(Build.ArtifactStagingDirectory)'  # Specify the path to your application files
    enableCustomDeployment: true
    deploymentMethod: 'auto'



