trigger:
  branches:
    include:
      - main  # Specify the branch to trigger the pipeline (e.g., main, master)

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool to use for running the pipeline (e.g., Ubuntu, Windows)

stages:
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'  # Path to the source code folder
        Contents: '**'  # Copy all files and folders recursively
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Copy to the artifact staging directory

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'Azure Web App Service Connection'  # Use the name of your service connection
        appName: 'theracingpuzzle'  # Name of the Azure Web App (theracingpuzzle)
        package: '$(Build.ArtifactStagingDirectory)'  # Path to the artifacts to deploy
        deployToSlotOrASE: true  # Set to true if deploying to a slot or App Service Environment (ASE)
        ResourceGroupName: 'theracingpuzzle_group'  # Name of the Azure Resource Group (theracingpuzzle_group)

    - task: AzureCLI@2
      displayName: 'Update web.config for PHP'
      inputs:
        azureSubscription: 'Azure Web App Service Connection'  # Use the name of your service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config appsettings set --name theracingpuzzle --resource-group theracingpuzzle_group --settings PHP_INI_SCAN_DIR=ini


