trigger:
  branches:
    include:
      - main  # Adjust to your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(Build.SourcesDirectory)  # Add this script task to print the source directory
  displayName: 'Print Source Directory'  # Optional display name for the task

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'  # Copy all files from the source directory
    Contents: '**/*'  # Include all files and folders recursively
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Copy to the staging directory

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/controllers'  # Explicitly include the controllers folder
    Contents: '**/*'  # Include all files and folders recursively
    TargetFolder: '$(Build.ArtifactStagingDirectory)/controllers'  # Copy to the staging directory under controllers

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Publish the files from the staging directory as build artifacts
    ArtifactName: 'drop'  # Name of the artifact
    publishLocation: 'Container'  # Publish to Azure Pipelines artifacts

- task: Npm@1  # Example npm build task
  displayName: 'npm install and build'
  inputs:
    command: 'install'  # npm command to execute
    workingDir: '$(Build.SourcesDirectory)'  # Path to your project's directory containing package.json

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Web App Service Connection'  # Specify the name of your Azure service connection
    appName: 'theracingpuzzle'  # Specify the name of your Azure Web App
    package: '$(Build.ArtifactStagingDirectory)'  # Specify the path to your application files
    enableCustomDeployment: true
    deploymentMethod: 'auto'




